### ISSUE TITLE
Enhancement: Option to embed OCR text in image's metadata

### ISSUE THREAD

**Issue by minig0d** [johnlinp/meme-ocr#11]
Have been wanting to do this for a long time... parse all the memes on my computer, OCR them and embed the text in the file's metadata so you could then search for meme's by the text...

Should be very easy for someone who knows Python... unfortunately, I don't... but example webpage showing exactly how to do it...
https://codezup.com/create-write-metadata-file-python/

**Comment by johnlinp** [comment]
`meme-ocr` is a library to focus on doing OCR. Writing the text back to the image metadata is out of the scope. You can develop your own application to do it with the help of `meme-ocr`.
